//Exception Handling:
/*try {
// Your Code Here
}
catch(ex){
// Exception here
}*/

void main() {
  /*var result = 4~/0;
  print(result);*/

//try on
/*try {
  var result = 4~/0;
  print(result);
} on
IntegerDivisionByZeroException {
  print('Can not Divided by Zero');
  }*/


  //try catch
/*  try {
    var result = 4~/0;
    print(result);
  } catch(e) {
    print(e);
  }*/

/*  int a = 12;
  int b = 0;
  int res;
  try {
    res = a ~/ b;
  } on UnsupportedError {
    print('Cannot divide by zero');
  } catch (ex) {
    print(ex);
  } finally {
    print('Finally block always executed');
  }
 */

  //try on catch
/*  try {
    var result = 4~/0;
    print(result);
  } on
  IntegerDivisionByZeroException
    catch (e) {
      print(e);
    }*/

/*  //try on catch
  try {
    var result = 4~/0;
    print(result);
  } on
  IntegerDivisionByZeroException
  catch (e) {
    print(e);
  } finally {
    print('Finally Always Executes');
  }*/
}